" Ensure Vim runs in non-compatible mode
set nocompatible

" Display settings
set number
set relativenumber
set cursorline
set cursorcolumn
set clipboard=unnamedplus

" Indentation settings
set shiftwidth=4
set tabstop=4
set expandtab
set softtabstop=4

" Backup and undo settings
set nobackup
set undodir=~/.vim/undodir
set undofile

" Scrolling and search settings
set scrolloff=10
set nowrap
set incsearch
set ignorecase
set smartcase
set nohlsearch

" Command and completion settings
set showcmd
set showmode
set showmatch
set history=1000
set wildmenu
set wildmode=longest:full,full
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildignorecase

" Mouse support
set mouse=a

" Code folding
set foldmethod=marker
set foldexpr=nvim_treesitter#foldexpr()
set foldmethod=expr
set foldenable

" Plugin manager and plugins (vim-plug)
call plug#begin('~/.vim/plugged')

" Git integration
Plug 'tpope/vim-fugitive'
Plug 'lewis6991/gitsigns.nvim'
Plug 'github/copilot.vim'

" Enable Copilot
let g:copilot_no_tab_map = v:true
imap <silent><script><expr> <C-J> copilot#Accept("\<CR>")

" LSP, completion, and linting
Plug 'neovim/nvim-lspconfig'
Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'
Plug 'jose-elias-alvarez/null-ls.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'saadparwaiz1/cmp_luasnip'
Plug 'L3MON4D3/LuaSnip'
Plug 'nvim-lua/plenary.nvim'

" Debugging
Plug 'mfussenegger/nvim-dap'

" File navigation
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }

" Status bar
Plug 'hoob3rt/lualine.nvim'

" Formatting and utility plugins
Plug 'tpope/vim-commentary'
Plug 'jiangmiao/auto-pairs'
Plug 'dense-analysis/ale'

call plug#end()


